# Generated by Django 5.0.14 on 2025-08-07 15:26

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='category_type',
            field=models.CharField(choices=[('news', '新闻'), ('creative', '创意'), ('industry', '行业'), ('research', '研究'), ('events', '活动')], default='news', max_length=20, verbose_name='分类类型'),
        ),
        migrations.AddField(
            model_name='channel',
            name='description',
            field=models.TextField(blank=True, verbose_name='分类描述'),
        ),
        migrations.AddField(
            model_name='channel',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='图标类名'),
        ),
        migrations.CreateModel(
            name='CreativeWorkPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateTimeField(db_index=True, verbose_name='发布日期')),
                ('agency', models.CharField(max_length=200, verbose_name='代理公司')),
                ('client', models.CharField(max_length=200, verbose_name='客户')),
                ('campaign_name', models.CharField(blank=True, max_length=200, verbose_name='活动名称')),
                ('category', models.CharField(choices=[('advertising', '广告'), ('design', '设计'), ('digital', '数字营销'), ('branding', '品牌'), ('social', '社交媒体'), ('video', '视频'), ('print', '平面'), ('outdoor', '户外')], default='advertising', max_length=20, verbose_name='创意类别')),
                ('awards', models.TextField(blank=True, verbose_name='获奖情况')),
                ('video_url', models.URLField(blank=True, verbose_name='视频链接')),
                ('project_url', models.URLField(blank=True, verbose_name='项目链接')),
                ('brief', models.TextField(blank=True, verbose_name='项目简介')),
                ('solution', models.TextField(blank=True, verbose_name='解决方案')),
                ('results', models.TextField(blank=True, verbose_name='项目成果')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='精选作品')),
                ('feature_rank', models.IntegerField(db_index=True, default=0, verbose_name='精选排序')),
                ('channels', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='creative_works', to='news.channel')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('tags', modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='news.ArticleTag', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='IndustryEventPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('event_date', models.DateTimeField(verbose_name='活动日期')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='结束日期')),
                ('location', models.CharField(max_length=200, verbose_name='活动地点')),
                ('organizer', models.CharField(max_length=200, verbose_name='主办方')),
                ('event_type', models.CharField(choices=[('conference', '会议'), ('awards', '颁奖典礼'), ('workshop', '工作坊'), ('exhibition', '展览'), ('networking', '社交活动'), ('webinar', '网络研讨会')], default='conference', max_length=20, verbose_name='活动类型')),
                ('registration_url', models.URLField(blank=True, verbose_name='报名链接')),
                ('ticket_price', models.CharField(blank=True, max_length=100, verbose_name='票价信息')),
                ('description', models.TextField(verbose_name='活动描述')),
                ('agenda', models.TextField(blank=True, verbose_name='活动议程')),
                ('speakers', models.TextField(blank=True, verbose_name='演讲嘉宾')),
                ('channels', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='events', to='news.channel')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('tags', modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='news.ArticleTag', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ResearchReportPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('publish_date', models.DateTimeField(db_index=True, verbose_name='发布日期')),
                ('report_type', models.CharField(choices=[('industry', '行业报告'), ('consumer', '消费者洞察'), ('trend', '趋势分析'), ('case_study', '案例研究'), ('whitepaper', '白皮书'), ('survey', '调研报告')], default='industry', max_length=20, verbose_name='报告类型')),
                ('author', models.CharField(max_length=200, verbose_name='作者/机构')),
                ('download_url', models.URLField(blank=True, verbose_name='下载链接')),
                ('is_free', models.BooleanField(default=True, verbose_name='免费下载')),
                ('summary', models.TextField(verbose_name='报告摘要')),
                ('key_findings', models.TextField(blank=True, verbose_name='关键发现')),
                ('methodology', models.TextField(blank=True, verbose_name='研究方法')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='精选报告')),
                ('channels', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='reports', to='news.channel')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('tags', modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='news.ArticleTag', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
