# Generated by Django 5.0.14 on 2025-08-07 06:34

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '__first__'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('modules', wagtail.fields.StreamField([('channel', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.snippets.blocks.SnippetChooserBlock', (), {'required': True, 'target_model': 'news.Channel'}), 2: ('wagtail.blocks.IntegerBlock', (), {'default': 8, 'max_value': 50, 'min_value': 1}), 3: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('-is_featured,-feature_rank,-date', '置顶优先/最新'), ('-date', '最新')]}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('channel', 1), ('limit', 2), ('only_with_image', 3), ('ordering', 4)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FeaturedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('note', models.CharField(blank=True, max_length=120)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='news.articlepage')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_items', to='core.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeToggles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_limit', models.IntegerField(default=8)),
                ('only_with_image_default', models.BooleanField(default=False)),
                ('hot_time_window_hours', models.IntegerField(default=72)),
                ('featured_target', models.IntegerField(default=4, help_text='首页精选目标条数，不足时自动补齐')),
                ('module_backfill_cross_channel', models.BooleanField(default=False, help_text='模块不足位是否允许跨频道补齐')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
