# Generated by Django 5.0.14 on 2025-08-07 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hometoggles',
            options={'verbose_name': '首页设置', 'verbose_name_plural': '首页设置'},
        ),
        migrations.CreateModel(
            name='AdSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_enabled', models.BooleanField(default=False, help_text='是否在站点显示广告', verbose_name='启用广告')),
                ('header_ad_slot', models.CharField(blank=True, help_text='页面头部广告位的ID', max_length=100, verbose_name='头部广告位ID')),
                ('sidebar_ad_slot', models.CharField(blank=True, help_text='侧边栏广告位的ID', max_length=100, verbose_name='侧边栏广告位ID')),
                ('footer_ad_slot', models.CharField(blank=True, help_text='页面底部广告位的ID', max_length=100, verbose_name='底部广告位ID')),
                ('article_ad_slot', models.CharField(blank=True, help_text='文章内容中广告位的ID', max_length=100, verbose_name='文章内广告位ID')),
                ('ad_network', models.CharField(choices=[('google', 'Google AdSense'), ('baidu', '百度联盟'), ('tencent', '腾讯广告'), ('custom', '自定义')], default='google', max_length=50, verbose_name='广告网络')),
                ('ad_code', models.TextField(blank=True, help_text='自定义广告代码（HTML/JavaScript）', verbose_name='广告代码')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': '广告设置',
                'verbose_name_plural': '广告设置',
            },
        ),
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='站点默认的页面标题（60字符以内）', max_length=60, verbose_name='默认标题')),
                ('meta_description', models.CharField(blank=True, help_text='站点默认的页面描述（160字符以内）', max_length=160, verbose_name='默认描述')),
                ('meta_keywords', models.CharField(blank=True, help_text='站点默认的关键词，用逗号分隔', max_length=200, verbose_name='默认关键词')),
                ('google_analytics_id', models.CharField(blank=True, help_text='GA4的测量ID，如 G-XXXXXXXXXX', max_length=20, verbose_name='Google Analytics ID')),
                ('baidu_tongji_id', models.CharField(blank=True, help_text='百度统计的代码ID', max_length=50, verbose_name='百度统计ID')),
                ('robots_txt', models.TextField(blank=True, help_text='自定义robots.txt内容', verbose_name='Robots.txt内容')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'SEO设置',
                'verbose_name_plural': 'SEO设置',
            },
        ),
        migrations.CreateModel(
            name='SiteTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('default', '默认主题'), ('dark', '深色主题'), ('light', '浅色主题'), ('news', '新闻主题'), ('tech', '科技主题')], default='default', max_length=20, verbose_name='主题样式')),
                ('primary_color', models.CharField(default='#007bff', help_text='十六进制颜色值，如 #007bff', max_length=7, verbose_name='主色调')),
                ('logo_url', models.URLField(blank=True, help_text='站点Logo的URL地址', verbose_name='Logo地址')),
                ('favicon_url', models.URLField(blank=True, help_text='浏览器标签页图标地址', verbose_name='Favicon地址')),
                ('custom_css', models.TextField(blank=True, help_text='额外的CSS样式代码', verbose_name='自定义CSS')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': '站点主题',
                'verbose_name_plural': '站点主题',
            },
        ),
        migrations.CreateModel(
            name='SocialSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wechat_qr', models.URLField(blank=True, help_text='微信公众号二维码图片地址', verbose_name='微信二维码')),
                ('weibo_url', models.URLField(blank=True, help_text='官方微博主页地址', verbose_name='微博地址')),
                ('douyin_url', models.URLField(blank=True, help_text='官方抖音主页地址', verbose_name='抖音地址')),
                ('bilibili_url', models.URLField(blank=True, help_text='官方B站主页地址', verbose_name='B站地址')),
                ('contact_email', models.EmailField(blank=True, help_text='官方联系邮箱', max_length=254, verbose_name='联系邮箱')),
                ('contact_phone', models.CharField(blank=True, help_text='官方联系电话', max_length=20, verbose_name='联系电话')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': '社交媒体设置',
                'verbose_name_plural': '社交媒体设置',
            },
        ),
    ]
