# Generated by Django 5.0.14 on 2025-08-08 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('article_published', '发布文章'), ('comment_posted', '发表评论'), ('work_submitted', '提交作品'), ('event_attended', '参加活动'), ('report_downloaded', '下载报告')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户活动',
                'verbose_name_plural': '用户活动',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='公司')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='职位')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='行业')),
                ('bio', models.TextField(blank=True, verbose_name='个人简介')),
                ('website', models.URLField(blank=True, verbose_name='个人网站')),
                ('twitter', models.CharField(blank=True, max_length=100, verbose_name='Twitter')),
                ('linkedin', models.CharField(blank=True, max_length=100, verbose_name='LinkedIn')),
                ('is_contributor', models.BooleanField(default=False, verbose_name='是否为贡献者')),
                ('contributor_bio', models.TextField(blank=True, verbose_name='贡献者简介')),
                ('contributor_expertise', models.CharField(blank=True, max_length=200, verbose_name='专业领域')),
                ('articles_count', models.IntegerField(default=0, verbose_name='文章数量')),
                ('followers_count', models.IntegerField(default=0, verbose_name='关注者数量')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='头像')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '关注关系',
                'verbose_name_plural': '关注关系',
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
